version: '3.1'

services:
  
  node:
    build:
      context: /home/ubuntu/chatter/chatterbox
    restart: always
    ports:
     - 3200:3200
 
  nginx:
    build:
      context: /home/ubuntu/chatter/chatterbox/nginx
    restart: always
    ports:
      - 80:80

